server:
  port: 9000
  
spring:
  application:
    name: GATEWAY-SERVICE
    
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

